=== MarkM-Portfolio/profiles/sn.profiles/lwp/profiles.config.files/config.legacy.files/tapstage/profiles-types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- IBM Confidential                                                  -->
<!--                                                                   -->
<!-- OCO Source Materials                                              -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2001, 2012                                    -->
<!--                                                                   -->
<!-- The source code for this program is not published or otherwise    -->
<!-- divested of its trade secrets, irrespective of what has been      -->
<!-- deposited with the U.S. Copyright Office.                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<xsd:schema 
	targetNamespace="http://www.ibm.com/profiles-types"
	xmlns="http://www.ibm.com/profiles-types"
	xmlns:tns="http://www.ibm.com/profiles-types"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xsd:simpleType name="enumUpdatability">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="read" />	
			<xsd:enumeration value="readwrite" />						
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="enumRole">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="self" />	
			<xsd:enumeration value="colleague" />
			<xsd:enumeration value="contact" />			
			<xsd:enumeration value="tenant" />
			<xsd:enumeration value="authenticated" />
			<xsd:enumeration value="anonymous" />						
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="enumPermission">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="read" />	
			<xsd:enumeration value="readwrite" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="typeId">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="64"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="aclType">
		<xsd:attribute name="role" type="tns:enumRole" use="required" />			
		<xsd:attribute name="permission" type="tns:enumPermission" use="required" />			
	</xsd:complexType>
			
	<xsd:complexType name="propertyType">
		<xsd:sequence>
			<xsd:element name="ref" type="xsd:string" minOccurs="1" maxOccurs="1" />				 
			<xsd:element name="updatability" type="tns:enumUpdatability" minOccurs="1" maxOccurs="1" />
			<xsd:element name="required" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
			<xsd:element name="hidden" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
			<xsd:element name="acl" type="tns:aclType" minOccurs="0" maxOccurs="6" />								
		</xsd:sequence>
	</xsd:complexType>
			
	<xsd:complexType name="typeType">
		<xsd:sequence>
			<xsd:element name="parentId" type="tns:typeId" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="id" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="property" type="tns:propertyType" minOccurs="0" maxOccurs="unbounded"/>			
		</xsd:sequence>		
	</xsd:complexType>
	
	<xsd:complexType name="configType">
		<xsd:sequence>
			<xsd:element name="type" type="tns:typeType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="tns:typeId"/>
	</xsd:complexType>
			
	<xsd:element name="config" type="tns:configType"/>
	
</xsd:schema>

=== MarkM-Portfolio/profiles/sn.profiles/lwp/profiles.config.files/config.legacy.files/att/v4/profiles-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- IBM Confidential                                                  -->
<!--                                                                   -->
<!-- OCO Source Materials                                              -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2012                                          -->
<!--                                                                   -->
<!-- The source code for this program is not published or otherwise    -->
<!-- divested of its trade secrets, irrespective of what has been      -->
<!-- deposited with the U.S. Copyright Office.                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<config xmlns="http://www.ibm.com/profiles-types" xmlns:tns="http://www.ibm.com/profiles-config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pt="http://www.ibm.com/profiles-types"
	xsi:schemaLocation="http://www.ibm.com/profiles-types profiles-types.xsd"
	id="profiles-types">
	<type>
		<parentId>snx:person</parentId>
		<id>default</id>
		<property>
			<ref>jobResp</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>secretaryUid</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>bldgId</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>floor</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>officeName</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>telephoneNumber</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>ipTelephoneNumber</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>mobileNumber</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>pagerNumber</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>faxNumber</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>groupwareEmail</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>blogUrl</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>description</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
			<richText>true</richText>
		</property>
		<property>
			<ref>experience</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
			<richText>true</richText>
		</property>
		<property>
			<ref>profileLinks</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>timezone</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>employeeTypeCode</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>ConsCompany</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>BusGroupId</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>BusUnitName</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>Address</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>City</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>State</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>PostalCode</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>countryCode</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>reachMe</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>uid</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>skills</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>orgs</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>patents</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>languages</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>projects</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>degrees</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>certifications</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>colleges</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>gradSchool</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>highSchool</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>displayName</ref>
			<updatability>read</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>interests</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>favoriteMovies</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>favoriteMusic</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>favoriteQuote</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>favoriteSports</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>activities</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>favoriteTVShows</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>favoriteBooks</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>twitterId</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>linkedInId</ref>
			<updatability>readwrite</updatability>
			<hidden>false</hidden>
		</property>
	</type>
</config>

=== MarkM-Portfolio/profiles/sn.profiles/lwp/profiles.config.files/config.legacy.files/tapstage/profiles-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- IBM Confidential                                                  -->
<!--                                                                   -->
<!-- OCO Source Materials                                              -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2012                                          -->
<!--                                                                   -->
<!-- The source code for this program is not published or otherwise    -->
<!-- divested of its trade secrets, irrespective of what has been      -->
<!-- deposited with the U.S. Copyright Office.                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<config xmlns="http://www.ibm.com/profiles-types" xmlns:tns="http://www.ibm.com/profiles-config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pt="http://www.ibm.com/profiles-types"
	xsi:schemaLocation="http://www.ibm.com/profiles-types profiles-types.xsd"
	id="profiles-types">
	<type>
		<parentId>snx:person</parentId>
		<id>default</id>
		<property>
			<ref>jobResp</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>secretaryUid</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>bldgId</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>floor</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>officeName</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>telephoneNumber</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>ipTelephoneNumber</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>mobileNumber</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>pagerNumber</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>faxNumber</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>groupwareEmail</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>blogUrl</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>description</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>experience</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>profileLinks</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
		<property>
			<ref>timezone</ref>
			<updatability>readwrite</updatability>
			<required>false</required>
			<hidden>false</hidden>
		</property>
	</type>
</config>
