=== MarkM-Portfolio/profiles/sn.profiles/lwp/profiles.config.files/internal/internal-profiles-policy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- IBM Confidential                                                  -->
<!--                                                                   -->
<!-- OCO Source Materials                                              -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2001, 2015                                    -->
<!--                                                                   -->
<!-- The source code for this program is not published or otherwise    -->
<!-- divested of its trade secrets, irrespective of what has been      -->
<!-- deposited with the U.S. Copyright Office.                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<xsd:schema 
	targetNamespace="http://www.ibm.com/profiles-policy"
	xmlns="http://www.ibm.com/profiles-policy"
	xmlns:tns="http://www.ibm.com/profiles-policy"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	
	<xsd:element name="config">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:features" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="features">
		<xsd:annotation>
			<xsd:documentation>
				This is for the user feature enablement based on their profile type
			</xsd:documentation>
		</xsd:annotation>		
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:feature" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="orgId" type="xsd:string" use="optional"/>
		</xsd:complexType>
		<xsd:unique name="FeatureUniqueness">
			<xsd:selector xpath="tns:feature"/>
			<xsd:field xpath="@name"/>
		</xsd:unique>
	</xsd:element>
	
	<xsd:element name="feature">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:profileType" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="name" use="required" >
				<xsd:simpleType>
				    <xsd:restriction base="xsd:string">
					<xsd:enumeration value="profile.board" />
					<xsd:enumeration value="profile.status" />
					<xsd:enumeration value="profile.photo" />
					<xsd:enumeration value="profile.pronunciation" />
					<xsd:enumeration value="profile.colleague" />
					<xsd:enumeration value="profile.reportTo" />
					<xsd:enumeration value="profile.peopleManaged" />
					<xsd:enumeration value="profile.tag" />
					<xsd:enumeration value="profile.following" />
					<xsd:enumeration value="profile.profile" />
					<xsd:enumeration value="profile.extension" />
					<xsd:enumeration value="profile.link" />
					<xsd:enumeration value="profile.connection" />
					<xsd:enumeration value="profile.activitystream" />
					<xsd:enumeration value="profile.sand" />
					<xsd:enumeration value="profile.search" />
					<xsd:enumeration value="profile.typeAhead" />
				    </xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="profileType">
	     <xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tns:acl" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="identity" type="tns:identity" use="optional"/>
			<xsd:attribute name="actorIdentity" type="tns:identity" use="optional"/>
			<xsd:attribute name="actorMode" type="tns:mode" use="optional"/>
			<xsd:attribute name="mode" type="tns:mode" use="optional"/>
			<xsd:attribute name="type" type="xsd:string" use="optional"/>
			<xsd:attribute name="actorType" type="xsd:string" use="optional"/>
			<xsd:attribute name="enabled" type="xsd:boolean" use="required"/>
	     </xsd:complexType>
	</xsd:element>

	<xsd:element name="acl">
		<xsd:annotation>
			<xsd:documentation>
				Main acl object
			</xsd:documentation>
		</xsd:annotation>
	    <xsd:complexType>
			<xsd:attribute name="name" use="required">
			    <xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="profile.profile.view" />
					<xsd:enumeration value="profile.profile.edit" />
					<xsd:enumeration value="profile.photo.view" />
					<xsd:enumeration value="profile.photo.update" />
					<xsd:enumeration value="profile.pronunciation.view" />
					<xsd:enumeration value="profile.pronunciation.update" />
					<xsd:enumeration value="profile.extension.view" />
					<xsd:enumeration value="profile.extension.edit" />
					<xsd:enumeration value="profile.link.update" />
					<xsd:enumeration value="profile.tag.add" />
					<xsd:enumeration value="profile.tag.view" />
					<xsd:enumeration value="profile.connection.view" />
					<xsd:enumeration value="profile.connection.message.view" />
					<xsd:enumeration value="profile.colleague.connect" />
					<xsd:enumeration value="profile.following.view" />
					<xsd:enumeration value="profile.following.add" />
					<xsd:enumeration value="profile.activitystream.targetted.event" />
					<xsd:enumeration value="profile.reportTo.view" />
					<xsd:enumeration value="profile.search.view" />
					<xsd:enumeration value="profile.search.guests.view" />
					<xsd:enumeration value="profile.search.organizations.view" />
					<xsd:enumeration value="profile.search.contacts.view" />
					<xsd:enumeration value="profile.sand.dyk.view" />
					<xsd:enumeration value="profile.sand.recommend.view" />
					<xsd:enumeration value="profile.sand.inCommon.view" />
					<xsd:enumeration value="profile.sand.socialPath.view" />
					<xsd:enumeration value="profile.typeAhead.view" />
					<xsd:enumeration value="profile.board.write.message" />
					<xsd:enumeration value="profile.board.write.comment" />
					<xsd:enumeration value="profile.board.recommend.message" />
					<xsd:enumeration value="profile.status.update" />
					<xsd:enumeration value="profile.status.view" />
				</xsd:restriction>
			    </xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="scope" use="required" type="tns:aclScope"/>
			<xsd:attribute name="dissallowNonAdminIfInactive" use="optional" type="xsd:boolean"/>
	    </xsd:complexType>
	</xsd:element>
	
	<xsd:simpleType name="aclScope">
		<xsd:annotation>
			<xsd:documentation>
				Currently supported acl scope settings for Profiles
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="none" />
			<xsd:enumeration value="admin" />
			<xsd:enumeration value="self" />
			<xsd:enumeration value="reader"/>
			<xsd:enumeration value="person_and_self" />
			<xsd:enumeration value="person_not_self" />
			<xsd:enumeration value="colleagues_and_self" />
			<xsd:enumeration value="colleagues_not_self" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="mode">
		<xsd:annotation>
			<xsd:documentation>
				Currently supported modes for Profiles
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="internal" />
			<xsd:enumeration value="external" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="identity">
		<xsd:annotation>
			<xsd:documentation>
				Currently supported identities/entitlements for Profiles
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="standard" />
			<xsd:enumeration value="freemium" />
			<xsd:enumeration value="pseudo" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== MarkM-Portfolio/profiles/sn.profiles/lwp/profiles.config.files/internal/internal-profiles-policy-mt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- IBM Confidential                                                  -->
<!--                                                                   -->
<!-- OCO Source Materials                                              -->
<!--                                                                   -->
<!-- Copyright IBM Corp. 2015, 2016                                    -->
<!--                                                                   -->
<!-- The source code for this program is not published or otherwise    -->
<!-- divested of its trade secrets, irrespective of what has been      -->
<!-- deposited with the U.S. Copyright Office.                         -->
<!--                                                                   -->
<!-- ***************************************************************** -->

<config id="profiles-policy"
		xmlns="http://www.ibm.com/profiles-policy" 
		xmlns:tns="http://www.ibm.com/profiles-policy" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.ibm.com/profiles-policy internal-profiles-policy.xsd">
<!--
	This is the internal policy features XML configuration file used for Multi-Tenant
	environments.  This configuration will be loaded into Profiles as not-modifiable.
	It is imperative that this be a complete list of all Out-Of-The-Box Policy 
	configurations as this is the baseline against which the customer-loaded 
	profiles-policy.xml file will be loaded from the LCC directory.  
	
	If a permission is not explicitly defined in here, it can be overridden from 
	the profiles-policy.xml	in the LCC directory.  So edit/remove stuff from here
	with care.
-->
	<features>
		<feature name="profile.board">
			<profileType enabled="true">
				<acl name="profile.board.write.message" scope="person_and_self" />
				<acl name="profile.board.write.comment" scope="person_and_self" />
				<acl name="profile.board.recommend.message" scope="person_and_self" />
			</profileType>
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false" />
		</feature>
		<feature name="profile.status">
			<profileType enabled="true">
				<acl name="profile.status.view" scope="reader" />
				<acl name="profile.status.update" scope="self" />
			</profileType>
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false" />
		</feature>
		<feature name="profile.search">
			<profileType enabled="true">
				<acl name="profile.search.view" scope="reader" />
				<acl name="profile.search.guests.view" scope="reader" />
				<acl name="profile.search.organizations.view" scope="reader" />
				<acl name="profile.search.contacts.view" scope="reader" />
			</profileType>
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false">
				<!-- acl name="profile.search.guests.view" scope="none" /-->
				<!-- acl name="profile.search.organizations.view" scope="none" /-->
				<!-- acl name="profile.search.contacts.view" scope="none" /-->
			</profileType>
		</feature>
		<feature name="profile.sand">
			<profileType enabled="true">
				<acl name="profile.sand.dyk.view" scope="reader" />
				<acl name="profile.sand.recommend.view" scope="reader" />
				<acl name="profile.sand.inCommon.view" scope="reader" />
				<acl name="profile.sand.socialPath.view" scope="reader" />
			</profileType>		
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false" />
		</feature>
		<feature name="profile.activitystream">
			<profileType enabled="true">
				<acl name="profile.activitystream.targetted.event" scope="person_and_self" />
			</profileType>		
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false" />
		</feature>
		<feature name="profile.connection">
			<profileType enabled="true">
				<acl name="profile.connection.view" scope="reader" />
				<acl name="profile.connection.message.view" scope="self" />
			</profileType>
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false" />
		</feature>
		<feature name="profile.colleague">
			<profileType enabled="true">
				<acl name="profile.colleague.connect" scope="person_not_self" />
			</profileType>
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false" />
		</feature>
		<feature name="profile.following">
			<profileType enabled="true">
				<acl name="profile.following.view" scope="reader" />
				<acl name="profile.following.add" scope="person_not_self" />
			</profileType>
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false" />
		</feature>
		<feature name="profile.peopleManaged">
			<profileType enabled="true" />	
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false" />
		</feature>
		<feature name="profile.reportTo">
			<profileType enabled="true">
				<acl name="profile.reportTo.view" scope="reader" />
			</profileType>
			<profileType actorMode="external" mode="external" enabled="false" />
			<profileType actorMode="external" mode="internal" enabled="false" />
		</feature>
		<feature name="profile.typeAhead">
			<profileType enabled="true">
				<acl name="profile.typeAhead.view" scope="reader" />
			</profileType>		
			<profileType actorMode="external" enabled="false" />
			<profileType mode="external" enabled="false" />
		</feature>
		<feature name="profile.tag">
			<profileType enabled="true">
				<acl name="profile.tag.view" scope="reader" />
				<acl name="profile.tag.add" scope="person_and_self" />
			</profileType>		
			<profileType actorMode="external" mode="external" enabled="true">
				<acl name="profile.tag.add" scope="self" />
			</profileType>
		</feature>
		<feature name="profile.profile">
			<profileType enabled="true">
				<acl name="profile.profile.view" scope="reader" />
				<acl name="profile.profile.edit" scope="self" />
			</profileType>
			<profileType actorMode="external" enabled="true">
				<acl name="profile.profile.view" scope="self" />
			</profileType>
		</feature>
		<feature name="profile.photo">
			<profileType enabled="true">
				<acl name="profile.photo.view" scope="reader" />
				<acl name="profile.photo.update" scope="self" />
			</profileType>
		</feature>
		<feature name="profile.pronunciation">
			<profileType enabled="true">
				<acl name="profile.pronunciation.view" scope="reader" />
				<acl name="profile.pronunciation.update" scope="self" />
			</profileType>
		</feature>
		<feature name="profile.extension">
			<profileType enabled="true">
				<acl name="profile.extension.view" scope="reader" />
				<acl name="profile.extension.edit" scope="self" />
			</profileType>
		</feature>
		<feature name="profile.link">
			<profileType enabled="true">
				<acl name="profile.link.update" scope="self" />
			</profileType>
		</feature>
	</features>
	
	<!-- freemium -->
	<features>
		<feature name="profile.board">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.status">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.search">
			<profileType identity="freemium" actorIdentity="freemium" mode="internal" actorMode="internal" enabled="true">
				<acl name="profile.search.view" scope="reader" />
				<!-- acl name="profile.search.guests.view" scope="none" /-->
				<!-- acl name="profile.search.organizations.view" scope="none" /-->
				<!-- acl name="profile.search.contacts.view" scope="none" /-->
			</profileType>
		</feature>
		<feature name="profile.sand">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.activitystream">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.connection">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.colleague">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.following">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.peopleManaged">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.reportTo">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.typeAhead">		
			<profileType identity="freemium" actorIdentity="freemium" mode="internal" actorMode="internal" enabled="true">
				<acl name="profile.typeAhead.view" scope="reader" />
			</profileType>
		</feature>
		<feature name="profile.tag">
			<profileType identity="freemium" actorIdentity="freemium" enabled="false" />
		</feature>
		<feature name="profile.profile">
			<profileType identity="freemium" actorIdentity="freemium" mode="internal" actorMode="internal" enabled="true">
				<acl name="profile.profile.view" scope="reader" />
				<acl name="profile.profile.edit" scope="self" />
			</profileType>
		</feature>
		<feature name="profile.photo">		
			<profileType identity="freemium" actorIdentity="freemium" mode="internal" actorMode="internal" enabled="true">
				<acl name="profile.photo.view" scope="reader" />
				<acl name="profile.photo.update" scope="self" />
			</profileType>
		</feature>
		<feature name="profile.pronunciation">		
			<profileType identity="freemium" actorIdentity="freemium" mode="internal" actorMode="internal" enabled="true">
				<acl name="profile.pronunciation.view" scope="reader" />
